name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/ui-screen/images/ellipse-24-bg.png
    - assets/ui-screen/images/checkbox.png
    - assets/ui-screen/images/ellipse-24-bg-FDw.png
    - assets/ui-screen/images/circle-left.png
    - assets/ui-screen/images/.png
    - assets/ui-screen/images/tick-square.png
    - assets/ui-screen/images/ellipse-30.png
    - assets/ui-screen/images/volume-up.png
    - assets/ui-screen/images/image-bg.png
    - assets/ui-screen/images/mask-group-PU1.png
    - assets/ui-screen/images/switch.png
    - assets/ui-screen/images/image-bg-tTf.png
    - assets/ui-screen/images/checkbox-SNy.png
    - assets/ui-screen/images/master.png
    - assets/ui-screen/images/key-light.png
    - assets/ui-screen/images/right.png
    - assets/ui-screen/images/circle-left-eFF.png
    - assets/ui-screen/images/circle-left-Zf3.png
    - assets/ui-screen/images/image-bg-78h.png
    - assets/ui-screen/images/rectangle-57-bg.png
    - assets/ui-screen/images/right-etm.png
    - assets/ui-screen/images/search.png
    - assets/ui-screen/images/-Xuo.png
    - assets/ui-screen/images/right-13b.png
    - assets/ui-screen/images/radio.png
    - assets/ui-screen/images/visa.png
    - assets/ui-screen/images/repeat.png
    - assets/ui-screen/images/circle-left-6BF.png
    - assets/ui-screen/images/circle-left-o5f.png
    - assets/ui-screen/images/switch-YZ3.png
    - assets/ui-screen/images/-Wkm.png
    - assets/ui-screen/images/checkbox-5J5.png
    - assets/ui-screen/images/tick-square-haM.png
    - assets/ui-screen/images/circle-left-ri9.png
    - assets/ui-screen/images/-S29.png
    - assets/ui-screen/images/rectangle.png
    - assets/ui-screen/images/right-k2H.png
    - assets/ui-screen/images/right-Hnu.png
    - assets/ui-screen/images/circle-right.png
    - assets/ui-screen/images/checkbox-jTs.png
    - assets/ui-screen/images/checkbox-qp1.png
    - assets/ui-screen/images/password.png
    - assets/ui-screen/images/group-4.png
    - assets/ui-screen/images/rectangle-j8h.png
    - assets/ui-screen/images/checkbox-TKb.png
    - assets/ui-screen/images/pause.png
    - assets/ui-screen/images/password-3VF.png
    - assets/ui-screen/images/image.png
    - assets/ui-screen/images/auto-group-93zt.png
    - assets/ui-screen/images/checkbox-F9P.png
    - assets/ui-screen/images/home.png
    - assets/ui-screen/images/circle-left-yLH.png
    - assets/ui-screen/images/emoji.png
    - assets/ui-screen/images/repeat-2Q5.png
    - assets/ui-screen/images/circle-left-naZ.png
    - assets/ui-screen/images/checkbox-773.png
    - assets/ui-screen/images/checkbox-TAu.png
    - assets/ui-screen/images/circle-left-j8R.png
    - assets/ui-screen/images/ellipse-24-bg-Pyf.png
    - assets/ui-screen/images/notification.png
    - assets/ui-screen/images/circle-left-4TP.png
    - assets/ui-screen/images/skip-fwd.png
    - assets/ui-screen/images/-Nys.png
    - assets/ui-screen/images/-9Uq.png
    - assets/ui-screen/images/circle-left-G3f.png
    - assets/ui-screen/images/delete.png
    - assets/ui-screen/images/-Q9s.png
    - assets/ui-screen/images/tick-square-A93.png
    - assets/ui-screen/images/-vtu.png
    - assets/ui-screen/images/rectangle-HjT.png
    - assets/ui-screen/images/skip-back.png
    - assets/ui-screen/images/dictation.png
    - assets/ui-screen/images/down.png
    - assets/ui-screen/images/right-mbB.png
    - assets/ui-screen/images/ellipse-30-fwT.png
    - assets/ui-screen/images/circle-left-Di5.png
    - assets/ui-screen/images/mute.png
    - assets/ui-screen/images/circle-left-3Jd.png
    - assets/ui-screen/images/video-play.png
    - assets/ui-screen/images/checkbox-MaD.png
    - assets/ui-screen/images/-Kmw.png
    - assets/ui-screen/images/right-8Ms.png
    - assets/ui-screen/images/circle-left-sKT.png
    - assets/ui-screen/images/skip-back-y7b.png
    - assets/ui-screen/images/radio-d3j.png
    - assets/ui-screen/images/mask-group.png
    - assets/ui-screen/images/radio-ki1.png
    - assets/ui-screen/images/right-4Eq.png
    - assets/ui-screen/images/skip-fwd-oy7.png
    - assets/ui-screen/images/down-CyB.png
    - assets/ui-screen/images/image-gry.png
    - assets/ui-screen/images/right-T3j.png
    - assets/ui-screen/images/circle-left-7ty.png
    - assets/ui-screen/images/image-bg-dG9.png
    - assets/ui-screen/images/-JPP.png
    - assets/ui-screen/images/checkbox-nbF.png
    - assets/ui-screen/images/right-DnM.png
    - assets/ui-screen/images/checkbox-Qnq.png
    - assets/ui-screen/images/image-grh.png
    - assets/ui-screen/images/radio-5Wd.png
    - assets/ui-screen/images/shift.png
    - assets/ui-screen/images/call.png
    - assets/ui-screen/images/circle-left-tFo.png
    - assets/ui-screen/images/image-omP.png
    - assets/ui-screen/images/date-picker.png
    - assets/ui-screen/images/play.png
    - assets/ui-screen/images/flame.png
    - assets/ui-screen/images/image-bg-cxd.png
    - assets/ui-screen/images/card.png
    - assets/ui-screen/images/background.png
    - assets/ui-screen/images/card-933.png
    - assets/ui-screen/images/down-LDb.png
    - assets/ui-screen/images/image-7oj.png
    - assets/ui-screen/images/image-cHB.png
    - assets/ui-screen/images/image-g1T.png
    - assets/ui-screen/images/image-bg-kR3.png
    - assets/ui-screen/images/chevron-right.png
    - assets/ui-screen/images/play-aD3.png
    - assets/ui-screen/images/flame-ySD.png
    - assets/ui-screen/images/down-vXo.png
    - assets/ui-screen/images/image-bg-PCq.png
    - assets/ui-screen/images/image-9JV.png
    - assets/ui-screen/images/rectangle-PEd.png
    - assets/ui-screen/images/input.png
    - assets/ui-screen/images/circle-left-tX7.png
    - assets/ui-screen/images/down-yNm.png
    - assets/ui-screen/images/key-light-mC9.png
    - assets/ui-screen/images/down-2hj.png
    - assets/ui-screen/images/auto-group-xj5e.png
    - assets/ui-screen/images/dictation-UB7.png
    - assets/ui-screen/images/image-bg-1U1.png
    - assets/ui-screen/images/home-B9F.png
    - assets/ui-screen/images/-QzZ.png
    - assets/ui-screen/images/image-bg-Eyb.png
    - assets/ui-screen/images/emoji-nhb.png
    - assets/ui-screen/images/image-bg-voo.png
    - assets/ui-screen/images/rectangle-DCy.png
    - assets/ui-screen/images/image-bg-d9f.png
    - assets/ui-screen/images/rectangle-Dy7.png
    - assets/ui-screen/images/input-K2u.png
    - assets/ui-screen/images/input-K2d.png
    - assets/ui-screen/images/image-u4y.png
    - assets/ui-screen/images/image-bg-3Q1.png
    - assets/ui-screen/images/shift-1Ju.png
    - assets/ui-screen/images/rectangle-6CD.png
    - assets/ui-screen/images/dictation-ttM.png
    - assets/ui-screen/images/image-7Sm.png
    - assets/ui-screen/images/key-light-TgH.png
    - assets/ui-screen/images/circle-left-Gvy.png
    - assets/ui-screen/images/rectangle-HLZ.png
    - assets/ui-screen/images/-W2H.png
    - assets/ui-screen/images/close-square.png
    - assets/ui-screen/images/-RaD.png
    - assets/ui-screen/images/shift-MWD.png
    - assets/ui-screen/images/emoji-PTT.png
    - assets/ui-screen/images/rectangle-mk9.png
    - assets/ui-screen/images/chevron-right-Zdw.png
    - assets/ui-screen/images/google.png
    - assets/ui-screen/images/hide.png
    - assets/ui-screen/images/google-oZo.png
    - assets/ui-screen/images/chevron-right-GWh.png
    - assets/ui-screen/images/apple.png
    - assets/ui-screen/images/show.png
    - assets/ui-screen/images/apple-X2M.png
    - assets/ui-screen/images/google-7yo.png
    - assets/ui-screen/images/google-T5w.png
    - assets/ui-screen/images/apple-GyB.png
    - assets/ui-screen/images/chevron-right-zs7.png
    - assets/ui-screen/images/hide-nny.png
    - assets/ui-screen/images/arrow-left.png
    - assets/ui-screen/images/tick-square-y4R.png
    - assets/ui-screen/images/venus.png
    - assets/ui-screen/images/chevron-right-wd7.png
    - assets/ui-screen/images/chevron-right-BED.png
    - assets/ui-screen/images/background-wJD.png
    - assets/ui-screen/images/arrow-left-jvD.png
    - assets/ui-screen/images/chevron-right-Pjb.png
    - assets/ui-screen/images/arrow-left-y5P.png
    - assets/ui-screen/images/apple-eFo.png
    - assets/ui-screen/images/arrow-left-Ajw.png
    - assets/ui-screen/images/chevron-right-7QH.png
    - assets/ui-screen/images/chevron-right-7qf.png
    - assets/ui-screen/images/background-UUD.png
    - assets/ui-screen/images/background-Ve5.png
    - assets/ui-screen/images/venus-yph.png
    - assets/ui-screen/images/mars.png
    - assets/ui-screen/images/chevron-right-apM.png
    - assets/ui-screen/images/background-Nof.png
    - assets/ui-screen/images/chevron-right-FPT.png
    - assets/ui-screen/images/background-cLu.png
    - assets/ui-screen/images/chevron-right-H8Z.png
    - assets/ui-screen/images/background-W69.png
    - assets/ui-screen/images/mars-Jcm.png
    - assets/ui-screen/images/mask-group-vVT.png
    - assets/ui-screen/images/background-Yp5.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
